"""Initial tables

Revision ID: 1ea11ee2c8ab
Revises: b0e905d6b158
Create Date: 2021-04-12 00:13:25.487001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea11ee2c8ab'
down_revision = 'b0e905d6b158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('usr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usr_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_id'), 'rating', ['id'], unique=False)
    op.create_table('auctionable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_cap', sa.Float(), nullable=True),
    sa.Column('starting_bid', sa.Float(), nullable=True),
    sa.Column('prod_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prod_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auctionable_id'), 'auctionable', ['id'], unique=False)
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('prod_sell', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prod_sell'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_id'), 'cart', ['id'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('usr_id', sa.Integer(), nullable=True),
    sa.Column('prod_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prod_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['usr_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_id'), 'comment', ['id'], unique=False)
    op.create_table('product_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.Column('prod_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['prod_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_category_id'), 'product_category', ['id'], unique=False)
    op.create_table('sellable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('prod_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prod_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sellable_id'), 'sellable', ['id'], unique=False)
    op.add_column('auction', sa.Column('current_bid', sa.Float(), nullable=True))
    op.add_column('auction', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('auction', sa.Column('prod_auc_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'auction', type_='foreignkey')
    op.create_foreign_key(None, 'auction', 'product', ['prod_auc_id'], ['id'])
    op.drop_column('auction', 'product_id')
    op.drop_column('auction', 'selling_price')
    op.add_column('product', sa.Column('img', sa.String(), nullable=True))
    op.add_column('product', sa.Column('usr_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'user', ['usr_id'], ['id'])
    op.drop_column('product', 'category')
    op.drop_column('product', 'reserv')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.add_column('product', sa.Column('reserv', sa.INTEGER(), nullable=True))
    op.add_column('product', sa.Column('category', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'usr_id')
    op.drop_column('product', 'img')
    op.add_column('auction', sa.Column('selling_price', sa.INTEGER(), nullable=True))
    op.add_column('auction', sa.Column('product_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'auction', type_='foreignkey')
    op.create_foreign_key(None, 'auction', 'product', ['product_id'], ['id'])
    op.drop_column('auction', 'prod_auc_id')
    op.drop_column('auction', 'duration')
    op.drop_column('auction', 'current_bid')
    op.drop_index(op.f('ix_sellable_id'), table_name='sellable')
    op.drop_table('sellable')
    op.drop_index(op.f('ix_product_category_id'), table_name='product_category')
    op.drop_table('product_category')
    op.drop_index(op.f('ix_comment_id'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_cart_id'), table_name='cart')
    op.drop_table('cart')
    op.drop_index(op.f('ix_auctionable_id'), table_name='auctionable')
    op.drop_table('auctionable')
    op.drop_index(op.f('ix_rating_id'), table_name='rating')
    op.drop_table('rating')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
