"""Initial tables

Revision ID: 40fed8c8f962
Revises: 
Create Date: 2021-04-22 22:54:51.170921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40fed8c8f962'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table('discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_id'), 'discount', ['id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('restocked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('bid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_amount', sa.Float(), nullable=True),
    sa.Column('usr_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['usr_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_id'), 'bid', ['id'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('usr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usr_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_id'), 'comment', ['id'], unique=False)
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('usr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usr_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('product_condition', sa.Enum('BRAND_NEW', 'BEST', 'GOOD', 'POOR', name='productcondition'), nullable=True),
    sa.Column('inventory_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('usr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['usr_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('usr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usr_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_id'), 'rating', ['id'], unique=False)
    op.create_table('shoppingsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usr_id', sa.Integer(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usr_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shoppingsession_id'), 'shoppingsession', ['id'], unique=False)
    op.create_table('auctionable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_cap', sa.Float(), nullable=True),
    sa.Column('starting_bid', sa.Float(), nullable=True),
    sa.Column('prod_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prod_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auctionable_id'), 'auctionable', ['id'], unique=False)
    op.create_table('auctionsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minimum_bid_amount', sa.Float(), nullable=True),
    sa.Column('auction_state', sa.Enum('CREATED', 'ENDED', 'CANCELED', 'ONGOING', name='auctionstate'), nullable=True),
    sa.Column('last_bid_at', sa.DateTime(), nullable=True),
    sa.Column('ending_at', sa.DateTime(), nullable=True),
    sa.Column('winning_bid_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['winning_bid_id'], ['bid.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auctionsession_id'), 'auctionsession', ['id'], unique=False)
    op.create_table('product_category',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], )
    )
    op.create_table('product_comment',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], )
    )
    op.create_table('product_image',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], )
    )
    op.create_table('sellable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('prod_id', sa.Integer(), nullable=True),
    sa.Column('discount_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discount_id'], ['discount.id'], ),
    sa.ForeignKeyConstraint(['prod_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sellable_id'), 'sellable', ['id'], unique=False)
    op.create_table('userdetail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usr_id', sa.Integer(), nullable=True),
    sa.Column('profile_pic_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profile_pic_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['usr_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userdetail_id'), 'userdetail', ['id'], unique=False)
    op.create_table('auction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('auction_winner_id', sa.Integer(), nullable=True),
    sa.Column('auctionable_id', sa.Integer(), nullable=True),
    sa.Column('auction_session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['auction_session_id'], ['auctionsession.id'], ),
    sa.ForeignKeyConstraint(['auction_winner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['auctionable_id'], ['auctionable.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_id'), 'auction', ['id'], unique=False)
    op.create_table('auction_bid',
    sa.Column('auction_session_id', sa.Integer(), nullable=True),
    sa.Column('bid_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auction_session_id'], ['auctionsession.id'], ),
    sa.ForeignKeyConstraint(['bid_id'], ['bid.id'], )
    )
    op.create_table('cartitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('sellalbe_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sellalbe_id'], ['sellable.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['shoppingsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartitem_id'), 'cartitem', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cartitem_id'), table_name='cartitem')
    op.drop_table('cartitem')
    op.drop_table('auction_bid')
    op.drop_index(op.f('ix_auction_id'), table_name='auction')
    op.drop_table('auction')
    op.drop_index(op.f('ix_userdetail_id'), table_name='userdetail')
    op.drop_table('userdetail')
    op.drop_index(op.f('ix_sellable_id'), table_name='sellable')
    op.drop_table('sellable')
    op.drop_table('product_image')
    op.drop_table('product_comment')
    op.drop_table('product_category')
    op.drop_index(op.f('ix_auctionsession_id'), table_name='auctionsession')
    op.drop_table('auctionsession')
    op.drop_index(op.f('ix_auctionable_id'), table_name='auctionable')
    op.drop_table('auctionable')
    op.drop_index(op.f('ix_shoppingsession_id'), table_name='shoppingsession')
    op.drop_table('shoppingsession')
    op.drop_index(op.f('ix_rating_id'), table_name='rating')
    op.drop_table('rating')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_image_id'), table_name='image')
    op.drop_table('image')
    op.drop_index(op.f('ix_comment_id'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_bid_id'), table_name='bid')
    op.drop_table('bid')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_discount_id'), table_name='discount')
    op.drop_table('discount')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
