"""Initial tables

Revision ID: 5aaa22a3347c
Revises: 745784f7711e
Create Date: 2021-04-10 14:08:43.762810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aaa22a3347c'
down_revision = '745784f7711e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
