"""Initial tables

Revision ID: a52c4a4d168f
Revises: 6abfb001cf51
Create Date: 2021-04-22 17:07:55.397676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a52c4a4d168f'
down_revision = '6abfb001cf51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
