"""Initial tables

Revision ID: b94a64183b9c
Revises: ec49bd05b3bf
Create Date: 2021-04-20 14:42:21.397359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b94a64183b9c'
down_revision = 'ec49bd05b3bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
