"""Initial tables

Revision ID: e915ca149bd8
Revises: a3d8b5c3a743
Create Date: 2021-04-14 11:16:30.194570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e915ca149bd8'
down_revision = 'a3d8b5c3a743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
