"""Initial tables

Revision ID: ec49bd05b3bf
Revises: 4d5d088a3e1e
Create Date: 2021-04-19 19:40:12.475903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec49bd05b3bf'
down_revision = '4d5d088a3e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
